# Generated by Django 3.2 on 2021-05-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=100, verbose_name='Specification key')),
                ('feature_name', models.CharField(max_length=100, verbose_name='Specification name')),
                ('postfix_for_value', models.CharField(blank=True, help_text="\n            For example, you can add postfix 'hours' for 'time without charge'. \n        ", max_length=20, null=True, verbose_name='Postfix for value')),
                ('use_in_filter', models.BooleanField(default=False, verbose_name='Use for filtering products in template')),
                ('filter_type', models.CharField(choices=[('checkbox', 'Checkbox'), ('radio', 'Radio button')], default='checkbox', max_length=20, verbose_name='Filter type')),
                ('filter_measure', models.CharField(help_text='Unit for measuring filters. Example: CPU frequency: GHz.', max_length=20, verbose_name='Unit for filter measuring')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatureValidators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_value', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Feature value')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Category')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productfeatures', verbose_name='Feature')),
            ],
        ),
    ]
