# Generated by Django 3.2 on 2021-04-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210430_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotebookProduct',
            new_name='Notebook',
        ),
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
